/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as TherapistPortalRouteImport } from './routes/therapist-portal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as JoinTherapistRouteImport } from './routes/join-therapist'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsSlugRouteImport } from './routes/therapists.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistPortalRoute = TherapistPortalRouteImport.update({
  id: '/therapist-portal',
  path: '/therapist-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTherapistRoute = JoinTherapistRouteImport.update({
  id: '/join-therapist',
  path: '/join-therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsSlugRoute = TherapistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TherapistsRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/gift-cards': typeof GiftCardsRoute
  '/join-therapist': typeof JoinTherapistRoute
  '/knowledge': typeof KnowledgeRoute
  '/locations': typeof LocationsRouteWithChildren
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/treatments': typeof TreatmentsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/therapists/$slug': typeof TherapistsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/gift-cards': typeof GiftCardsRoute
  '/join-therapist': typeof JoinTherapistRoute
  '/knowledge': typeof KnowledgeRoute
  '/locations': typeof LocationsRouteWithChildren
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/treatments': typeof TreatmentsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/therapists/$slug': typeof TherapistsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/gift-cards': typeof GiftCardsRoute
  '/join-therapist': typeof JoinTherapistRoute
  '/knowledge': typeof KnowledgeRoute
  '/locations': typeof LocationsRouteWithChildren
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/treatments': typeof TreatmentsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/therapists/$slug': typeof TherapistsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/areas'
    | '/booking'
    | '/contact'
    | '/cookies'
    | '/corporate'
    | '/dashboard'
    | '/gift-cards'
    | '/join-therapist'
    | '/knowledge'
    | '/locations'
    | '/membership'
    | '/privacy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/therapist-portal'
    | '/therapists'
    | '/treatments'
    | '/locations/$slug'
    | '/therapists/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/areas'
    | '/booking'
    | '/contact'
    | '/cookies'
    | '/corporate'
    | '/dashboard'
    | '/gift-cards'
    | '/join-therapist'
    | '/knowledge'
    | '/locations'
    | '/membership'
    | '/privacy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/therapist-portal'
    | '/therapists'
    | '/treatments'
    | '/locations/$slug'
    | '/therapists/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/areas'
    | '/booking'
    | '/contact'
    | '/cookies'
    | '/corporate'
    | '/dashboard'
    | '/gift-cards'
    | '/join-therapist'
    | '/knowledge'
    | '/locations'
    | '/membership'
    | '/privacy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/therapist-portal'
    | '/therapists'
    | '/treatments'
    | '/locations/$slug'
    | '/therapists/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasRoute: typeof AreasRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CorporateRoute: typeof CorporateRoute
  DashboardRoute: typeof DashboardRoute
  GiftCardsRoute: typeof GiftCardsRoute
  JoinTherapistRoute: typeof JoinTherapistRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TherapistPortalRoute: typeof TherapistPortalRoute
  TherapistsRoute: typeof TherapistsRouteWithChildren
  TreatmentsRoute: typeof TreatmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist-portal': {
      id: '/therapist-portal'
      path: '/therapist-portal'
      fullPath: '/therapist-portal'
      preLoaderRoute: typeof TherapistPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-therapist': {
      id: '/join-therapist'
      path: '/join-therapist'
      fullPath: '/join-therapist'
      preLoaderRoute: typeof JoinTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/$slug': {
      id: '/therapists/$slug'
      path: '/$slug'
      fullPath: '/therapists/$slug'
      preLoaderRoute: typeof TherapistsSlugRouteImport
      parentRoute: typeof TherapistsRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
  }
}

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface TherapistsRouteChildren {
  TherapistsSlugRoute: typeof TherapistsSlugRoute
}

const TherapistsRouteChildren: TherapistsRouteChildren = {
  TherapistsSlugRoute: TherapistsSlugRoute,
}

const TherapistsRouteWithChildren = TherapistsRoute._addFileChildren(
  TherapistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasRoute: AreasRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CorporateRoute: CorporateRoute,
  DashboardRoute: DashboardRoute,
  GiftCardsRoute: GiftCardsRoute,
  JoinTherapistRoute: JoinTherapistRoute,
  KnowledgeRoute: KnowledgeRoute,
  LocationsRoute: LocationsRouteWithChildren,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TherapistPortalRoute: TherapistPortalRoute,
  TherapistsRoute: TherapistsRouteWithChildren,
  TreatmentsRoute: TreatmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
